site_name: API Star
theme:
    name: null
    custom_dir: 'docs-theme'
pages:
    - Home: index.md
    - Topics:
        - Validation: validation.md
        - Documentation: documentation.md
        - API Client: api-client.md
        - Type System: type-system.md
