site_name: API Star
theme:
    name: null
    custom_dir: 'docs-theme'
pages:
    - Home: index.md
    - Tools:
        - Schema Validation: schema-validation.md
        - Documentation: documentation.md
        - API Client: api-client.md
    - Type System:
        - Types and Validators: type-system.md
        - JSON Schema: type-system.md
        - HTML Forms: type-system.md
        - API Validation: type-system.md
