#!venv/bin/python
import subprocess

import click
import os


# By default we want to run scripts from the virtualenv, without
# requiring it to be activated.
if os.path.exists('venv'):
    PATH = os.path.join('venv', 'bin')
else:
    PATH = ''



@click.command()
def lint():
    commands = [
        [os.path.join(PATH, 'flake8'), 'apistar', 'tests'],
        [os.path.join(PATH, 'isort'), '--check-only', '--recursive', 'apistar', 'tests']
    ]

    for command in commands:
        error = 0

        try:
            click.echo('Running {}'.format(' '.join(command)))

            subprocess.run(command, check=True)
        except subprocess.CalledProcessError:
            error = 1

    exit_command = 'exit {}'.format(error)
    subprocess.run(exit_command, shell=True, check=True)


if __name__ == '__main__':
    lint()
