#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}flake8 apistar tests
${PREFIX}isort apistar tests --recursive --check-only
# if ! expr "$TRAVIS_PYTHON_VERSION" : 'pypy'; then
#     ${PREFIX}mypy apistar tests --ignore-missing-imports
# fi
