#!/bin/sh -e

export VERSION=`cat pyproject.toml | grep ^version | sed "s/version = //" | sed "s/\"//g"`

find apistar -type f -name "*.py[co]" -delete
find apistar -type d -name __pycache__ -delete

poetry publish

echo "You probably want to also tag the version now:"
echo "git tag -a ${VERSION} -m 'version ${VERSION}'"
echo "git push --tags"

rm -r dist
