#!venv/bin/python
from subprocess import run
import os
import sys

import click
import pytest


@click.command()
@click.option('--cov', is_flag=True, help='Run tests with coverage.')
def test(cov):
    command = []

    if cov:
        command += ['--cov=apistar', '--cov-report=xml', '--cov-report=term']

    command += ['tests']

    # Ensure that apistar is on the PYTHONPATH
    cwd = os.getcwd()
    sys.path.insert(0, cwd)

    retcode = pytest.main(command)
    sys.exit(retcode)


if __name__ == '__main__':
    test()
